---
# Configuration file for Mega-Linter

VALIDATE_ALL_CODEBASE: true
APPLY_FIXES: all
DEFAULT_BRANCH: main
DISABLE:
  - COPYPASTE
  - SPELL
  - MARKDOWN
  - JSON
  - REPOSITORY
  - DOCKERFILE
  - YAML
  - GO
  - GO_REVIVE
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
YAML_YAMLLINT_DISABLE_ERRORS: true
DISABLE_LINTERS:
  - ACTION_ACTIONLINT
  - YAML_V8R
  - YAML_PRETTIER
  - BASH_EXEC
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - DOCKERFILE_DOCKERFILELINT
  - GIT_GIT_DIFF
