apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-security-policy-auditor-binding
subjects:
- kind: ServiceAccount
  name: k8s-security-policy-auditor-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-security-policy-auditor-role
  apiGroup: rbac.authorization.k8s.io
